spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:h2:file:./librarydb/library;AUTO_SERVER=TRUE
    password: root
    user: root
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
springdoc:
  swagger-ui:
    path: /library.html
server:
  port: 8088