spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:h2:file:./db/library;AUTO_SERVER=TRUE
    password: root
    user: root
  h2:
    console:
      path: /h2-console
      enabled: true
  r2dbc:
    url: r2dbc:h2:file:///./db/library
    username: root
    password: root
springdoc:
  swagger-ui:
    path: /library.html
server:
  port: 8088