spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
springdoc:
  swagger-ui:
    path: /library.html
server:
  port: 8088
  error:
    include-message: always